
modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="minecraftmod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Minecraft Mod" #mandatory
authors="The Manghoes" #optional
description='''
This is a description of our mod

'''
